{{- if .Values.datastore.writer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openslides.fullname" . }}-datastore-writer
  labels:
    {{- include "openslides.labels" . | nindent 4 }}
    app.kubernetes.io/component: datastore-writer
spec:
  replicas: {{ .Values.datastore.writer.replicaCount }}
  selector:
    matchLabels:
      {{- include "openslides.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: datastore-writer
  template:
    metadata:
      labels:
        {{- include "openslides.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: datastore-writer
    spec:
      automountServiceAccountToken: false
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: datastore-writer
          image: {{ include "openslides.image" (dict "global" .Values.global "image" .Values.datastore.writer.image) }}
          imagePullPolicy: {{ .Values.datastore.writer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.datastore.writer.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "openslides.configmapName" . }}
          env:
            - name: DATASTORE_DATABASE_HOST
              value: {{ include "openslides.postgresql.host" . | quote }}
            - name: DATASTORE_DATABASE_PORT
              value: "5432"
            - name: DATASTORE_DATABASE_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: DATASTORE_DATABASE_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DATASTORE_DATABASE_PASSWORD_FILE
              value: "/run/secrets/postgres_password"
          volumeMounts:
            - name: secrets
              mountPath: /run/secrets
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.datastore.writer.resources | nindent 12 }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "openslides.fullname" . }}-postgresql
            items:
              - key: password
                path: postgres_password
{{- end }}
