{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openslides.fullname" . }}-proxy
  labels:
    {{- include "openslides.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "openslides.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "openslides.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      automountServiceAccountToken: false
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ include "openslides.image" (dict "global" .Values.global "image" .Values.proxy.image) }}
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "openslides.configmapName" . }}
          env:
            - name: EXTERNAL_ADDRESS
              value: {{ .Values.global.domain | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
{{- end }}
