{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "openslides.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "openslides.postgresql.host" . }}
{{- end }}
